[pytest]
markers =
    slow: Mark a test as slow-running, e.g., for tests that take longer to execute.
    ubsan: Mark a test to run with undefined behavior sanitizer (UBSAN).
    complex: Mark a test as complex.
pythonpath = . python
