// Code generated by Thrift Compiler (0.22.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	thrift "github.com/apache/thrift/lib/go/thrift"
	infinity "github.com/infiniflow/infinity-go-sdk/internal/thrift"
)

var _ = infinity.GoUnusedProtection__

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  CommonResponse Connect(ConnectRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse Disconnect(CommonRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse CreateDatabase(CreateDatabaseRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse DropDatabase(DropDatabaseRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse CreateTable(CreateTableRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse DropTable(DropTableRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse RenameTable(RenameTableRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse Insert(InsertRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse Import(ImportRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse Export(ExportRequest request)")
	fmt.Fprintln(os.Stderr, "  SelectResponse Select(SelectRequest request)")
	fmt.Fprintln(os.Stderr, "  SelectResponse Explain(ExplainRequest request)")
	fmt.Fprintln(os.Stderr, "  DeleteResponse Delete(DeleteRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse Update(UpdateRequest request)")
	fmt.Fprintln(os.Stderr, "  ListDatabaseResponse ListDatabase(ListDatabaseRequest request)")
	fmt.Fprintln(os.Stderr, "  ListTableResponse ListTable(ListTableRequest request)")
	fmt.Fprintln(os.Stderr, "  ListIndexResponse ListIndex(ListIndexRequest request)")
	fmt.Fprintln(os.Stderr, "  ShowTableResponse ShowTable(ShowTableRequest request)")
	fmt.Fprintln(os.Stderr, "  SelectResponse ShowColumns(ShowColumnsRequest request)")
	fmt.Fprintln(os.Stderr, "  ShowDatabaseResponse ShowDatabase(ShowDatabaseRequest request)")
	fmt.Fprintln(os.Stderr, "  SelectResponse ShowSegments(ShowSegmentsRequest request)")
	fmt.Fprintln(os.Stderr, "  ShowSegmentResponse ShowSegment(ShowSegmentRequest request)")
	fmt.Fprintln(os.Stderr, "  SelectResponse ShowBlocks(ShowBlocksRequest request)")
	fmt.Fprintln(os.Stderr, "  ShowBlockResponse ShowBlock(ShowBlockRequest request)")
	fmt.Fprintln(os.Stderr, "  ShowBlockColumnResponse ShowBlockColumn(ShowBlockColumnRequest request)")
	fmt.Fprintln(os.Stderr, "  ShowCurrentNodeResponse ShowCurrentNode(ShowCurrentNodeRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse GetDatabase(GetDatabaseRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse GetTable(GetTableRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse CreateIndex(CreateIndexRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse DropIndex(DropIndexRequest request)")
	fmt.Fprintln(os.Stderr, "  ShowIndexResponse ShowIndex(ShowIndexRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse Optimize(OptimizeRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse AlterIndex(AlterIndexRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse AddColumns(AddColumnsRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse DropColumns(DropColumnsRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse Cleanup(CommonRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse DumpIndex(DumpIndexRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse Command(CommandRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse Flush(FlushRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse Compact(CompactRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse CreateTableSnapshot(CreateTableSnapshotRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse CreateDatabaseSnapshot(CreateDatabaseSnapshotRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse CreateSystemSnapshot(CreateSystemSnapshotRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse RestoreSnapshot(RestoreSnapshotRequest request)")
	fmt.Fprintln(os.Stderr, "  ShowSnapshotResponse ShowSnapshot(ShowSnapshotRequest request)")
	fmt.Fprintln(os.Stderr, "  ListSnapshotsResponse ListSnapshots(ListSnapshotsRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse DropSnapshot(DropSnapshotRequest request)")
	fmt.Fprintln(os.Stderr, "  CommonResponse SetConfig(SetConfigRequest request)")
	fmt.Fprintln(os.Stderr, "  ShowConfigResponse ShowConfig(ShowConfigRequest request)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
	var m map[string]string = h
	return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
	parts := strings.Split(value, ": ")
	if len(parts) != 2 {
		return fmt.Errorf("header should be of format 'Key: Value'")
	}
	h[parts[0]] = parts[1]
	return nil
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	headers := make(httpHeaders)
	var parsedUrl *url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
	flag.Parse()
	
	if len(urlString) > 0 {
		var err error
		parsedUrl, err = url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}
	
	cmd := flag.Arg(0)
	var err error
	var cfg *thrift.TConfiguration = nil
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
		if len(headers) > 0 {
			httptrans := trans.(*thrift.THttpClient)
			for key, value := range headers {
				httptrans.SetHeader(key, value)
			}
		}
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans = thrift.NewTSocketConf(net.JoinHostPort(host, portStr), cfg)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransportConf(trans, cfg)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactoryConf(cfg)
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactoryConf(cfg)
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryConf(cfg)
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	iprot := protocolFactory.GetProtocol(trans)
	oprot := protocolFactory.GetProtocol(trans)
	client := infinity.NewInfinityServiceClient(thrift.NewTStandardClient(iprot, oprot))
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}
	
	switch cmd {
	case "Connect":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Connect requires 1 args")
			flag.Usage()
		}
		arg422 := flag.Arg(1)
		mbTrans423 := thrift.NewTMemoryBufferLen(len(arg422))
		defer mbTrans423.Close()
		_, err424 := mbTrans423.WriteString(arg422)
		if err424 != nil {
			Usage()
			return
		}
		factory425 := thrift.NewTJSONProtocolFactory()
		jsProt426 := factory425.GetProtocol(mbTrans423)
		argvalue0 := infinity.NewConnectRequest()
		err427 := argvalue0.Read(context.Background(), jsProt426)
		if err427 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Connect(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Disconnect":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Disconnect requires 1 args")
			flag.Usage()
		}
		arg428 := flag.Arg(1)
		mbTrans429 := thrift.NewTMemoryBufferLen(len(arg428))
		defer mbTrans429.Close()
		_, err430 := mbTrans429.WriteString(arg428)
		if err430 != nil {
			Usage()
			return
		}
		factory431 := thrift.NewTJSONProtocolFactory()
		jsProt432 := factory431.GetProtocol(mbTrans429)
		argvalue0 := infinity.NewCommonRequest()
		err433 := argvalue0.Read(context.Background(), jsProt432)
		if err433 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Disconnect(context.Background(), value0))
		fmt.Print("\n")
		break
	case "CreateDatabase":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateDatabase requires 1 args")
			flag.Usage()
		}
		arg434 := flag.Arg(1)
		mbTrans435 := thrift.NewTMemoryBufferLen(len(arg434))
		defer mbTrans435.Close()
		_, err436 := mbTrans435.WriteString(arg434)
		if err436 != nil {
			Usage()
			return
		}
		factory437 := thrift.NewTJSONProtocolFactory()
		jsProt438 := factory437.GetProtocol(mbTrans435)
		argvalue0 := infinity.NewCreateDatabaseRequest()
		err439 := argvalue0.Read(context.Background(), jsProt438)
		if err439 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateDatabase(context.Background(), value0))
		fmt.Print("\n")
		break
	case "DropDatabase":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DropDatabase requires 1 args")
			flag.Usage()
		}
		arg440 := flag.Arg(1)
		mbTrans441 := thrift.NewTMemoryBufferLen(len(arg440))
		defer mbTrans441.Close()
		_, err442 := mbTrans441.WriteString(arg440)
		if err442 != nil {
			Usage()
			return
		}
		factory443 := thrift.NewTJSONProtocolFactory()
		jsProt444 := factory443.GetProtocol(mbTrans441)
		argvalue0 := infinity.NewDropDatabaseRequest()
		err445 := argvalue0.Read(context.Background(), jsProt444)
		if err445 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DropDatabase(context.Background(), value0))
		fmt.Print("\n")
		break
	case "CreateTable":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateTable requires 1 args")
			flag.Usage()
		}
		arg446 := flag.Arg(1)
		mbTrans447 := thrift.NewTMemoryBufferLen(len(arg446))
		defer mbTrans447.Close()
		_, err448 := mbTrans447.WriteString(arg446)
		if err448 != nil {
			Usage()
			return
		}
		factory449 := thrift.NewTJSONProtocolFactory()
		jsProt450 := factory449.GetProtocol(mbTrans447)
		argvalue0 := infinity.NewCreateTableRequest()
		err451 := argvalue0.Read(context.Background(), jsProt450)
		if err451 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateTable(context.Background(), value0))
		fmt.Print("\n")
		break
	case "DropTable":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DropTable requires 1 args")
			flag.Usage()
		}
		arg452 := flag.Arg(1)
		mbTrans453 := thrift.NewTMemoryBufferLen(len(arg452))
		defer mbTrans453.Close()
		_, err454 := mbTrans453.WriteString(arg452)
		if err454 != nil {
			Usage()
			return
		}
		factory455 := thrift.NewTJSONProtocolFactory()
		jsProt456 := factory455.GetProtocol(mbTrans453)
		argvalue0 := infinity.NewDropTableRequest()
		err457 := argvalue0.Read(context.Background(), jsProt456)
		if err457 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DropTable(context.Background(), value0))
		fmt.Print("\n")
		break
	case "RenameTable":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RenameTable requires 1 args")
			flag.Usage()
		}
		arg458 := flag.Arg(1)
		mbTrans459 := thrift.NewTMemoryBufferLen(len(arg458))
		defer mbTrans459.Close()
		_, err460 := mbTrans459.WriteString(arg458)
		if err460 != nil {
			Usage()
			return
		}
		factory461 := thrift.NewTJSONProtocolFactory()
		jsProt462 := factory461.GetProtocol(mbTrans459)
		argvalue0 := infinity.NewRenameTableRequest()
		err463 := argvalue0.Read(context.Background(), jsProt462)
		if err463 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RenameTable(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Insert":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Insert requires 1 args")
			flag.Usage()
		}
		arg464 := flag.Arg(1)
		mbTrans465 := thrift.NewTMemoryBufferLen(len(arg464))
		defer mbTrans465.Close()
		_, err466 := mbTrans465.WriteString(arg464)
		if err466 != nil {
			Usage()
			return
		}
		factory467 := thrift.NewTJSONProtocolFactory()
		jsProt468 := factory467.GetProtocol(mbTrans465)
		argvalue0 := infinity.NewInsertRequest()
		err469 := argvalue0.Read(context.Background(), jsProt468)
		if err469 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Insert(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Import":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Import requires 1 args")
			flag.Usage()
		}
		arg470 := flag.Arg(1)
		mbTrans471 := thrift.NewTMemoryBufferLen(len(arg470))
		defer mbTrans471.Close()
		_, err472 := mbTrans471.WriteString(arg470)
		if err472 != nil {
			Usage()
			return
		}
		factory473 := thrift.NewTJSONProtocolFactory()
		jsProt474 := factory473.GetProtocol(mbTrans471)
		argvalue0 := infinity.NewImportRequest()
		err475 := argvalue0.Read(context.Background(), jsProt474)
		if err475 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Import(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Export":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Export requires 1 args")
			flag.Usage()
		}
		arg476 := flag.Arg(1)
		mbTrans477 := thrift.NewTMemoryBufferLen(len(arg476))
		defer mbTrans477.Close()
		_, err478 := mbTrans477.WriteString(arg476)
		if err478 != nil {
			Usage()
			return
		}
		factory479 := thrift.NewTJSONProtocolFactory()
		jsProt480 := factory479.GetProtocol(mbTrans477)
		argvalue0 := infinity.NewExportRequest()
		err481 := argvalue0.Read(context.Background(), jsProt480)
		if err481 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Export(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Select":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Select requires 1 args")
			flag.Usage()
		}
		arg482 := flag.Arg(1)
		mbTrans483 := thrift.NewTMemoryBufferLen(len(arg482))
		defer mbTrans483.Close()
		_, err484 := mbTrans483.WriteString(arg482)
		if err484 != nil {
			Usage()
			return
		}
		factory485 := thrift.NewTJSONProtocolFactory()
		jsProt486 := factory485.GetProtocol(mbTrans483)
		argvalue0 := infinity.NewSelectRequest()
		err487 := argvalue0.Read(context.Background(), jsProt486)
		if err487 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Select(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Explain":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Explain requires 1 args")
			flag.Usage()
		}
		arg488 := flag.Arg(1)
		mbTrans489 := thrift.NewTMemoryBufferLen(len(arg488))
		defer mbTrans489.Close()
		_, err490 := mbTrans489.WriteString(arg488)
		if err490 != nil {
			Usage()
			return
		}
		factory491 := thrift.NewTJSONProtocolFactory()
		jsProt492 := factory491.GetProtocol(mbTrans489)
		argvalue0 := infinity.NewExplainRequest()
		err493 := argvalue0.Read(context.Background(), jsProt492)
		if err493 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Explain(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Delete":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Delete requires 1 args")
			flag.Usage()
		}
		arg494 := flag.Arg(1)
		mbTrans495 := thrift.NewTMemoryBufferLen(len(arg494))
		defer mbTrans495.Close()
		_, err496 := mbTrans495.WriteString(arg494)
		if err496 != nil {
			Usage()
			return
		}
		factory497 := thrift.NewTJSONProtocolFactory()
		jsProt498 := factory497.GetProtocol(mbTrans495)
		argvalue0 := infinity.NewDeleteRequest()
		err499 := argvalue0.Read(context.Background(), jsProt498)
		if err499 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Delete(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Update":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Update requires 1 args")
			flag.Usage()
		}
		arg500 := flag.Arg(1)
		mbTrans501 := thrift.NewTMemoryBufferLen(len(arg500))
		defer mbTrans501.Close()
		_, err502 := mbTrans501.WriteString(arg500)
		if err502 != nil {
			Usage()
			return
		}
		factory503 := thrift.NewTJSONProtocolFactory()
		jsProt504 := factory503.GetProtocol(mbTrans501)
		argvalue0 := infinity.NewUpdateRequest()
		err505 := argvalue0.Read(context.Background(), jsProt504)
		if err505 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Update(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ListDatabase":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ListDatabase requires 1 args")
			flag.Usage()
		}
		arg506 := flag.Arg(1)
		mbTrans507 := thrift.NewTMemoryBufferLen(len(arg506))
		defer mbTrans507.Close()
		_, err508 := mbTrans507.WriteString(arg506)
		if err508 != nil {
			Usage()
			return
		}
		factory509 := thrift.NewTJSONProtocolFactory()
		jsProt510 := factory509.GetProtocol(mbTrans507)
		argvalue0 := infinity.NewListDatabaseRequest()
		err511 := argvalue0.Read(context.Background(), jsProt510)
		if err511 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListDatabase(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ListTable":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ListTable requires 1 args")
			flag.Usage()
		}
		arg512 := flag.Arg(1)
		mbTrans513 := thrift.NewTMemoryBufferLen(len(arg512))
		defer mbTrans513.Close()
		_, err514 := mbTrans513.WriteString(arg512)
		if err514 != nil {
			Usage()
			return
		}
		factory515 := thrift.NewTJSONProtocolFactory()
		jsProt516 := factory515.GetProtocol(mbTrans513)
		argvalue0 := infinity.NewListTableRequest()
		err517 := argvalue0.Read(context.Background(), jsProt516)
		if err517 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListTable(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ListIndex":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ListIndex requires 1 args")
			flag.Usage()
		}
		arg518 := flag.Arg(1)
		mbTrans519 := thrift.NewTMemoryBufferLen(len(arg518))
		defer mbTrans519.Close()
		_, err520 := mbTrans519.WriteString(arg518)
		if err520 != nil {
			Usage()
			return
		}
		factory521 := thrift.NewTJSONProtocolFactory()
		jsProt522 := factory521.GetProtocol(mbTrans519)
		argvalue0 := infinity.NewListIndexRequest()
		err523 := argvalue0.Read(context.Background(), jsProt522)
		if err523 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListIndex(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ShowTable":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ShowTable requires 1 args")
			flag.Usage()
		}
		arg524 := flag.Arg(1)
		mbTrans525 := thrift.NewTMemoryBufferLen(len(arg524))
		defer mbTrans525.Close()
		_, err526 := mbTrans525.WriteString(arg524)
		if err526 != nil {
			Usage()
			return
		}
		factory527 := thrift.NewTJSONProtocolFactory()
		jsProt528 := factory527.GetProtocol(mbTrans525)
		argvalue0 := infinity.NewShowTableRequest()
		err529 := argvalue0.Read(context.Background(), jsProt528)
		if err529 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ShowTable(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ShowColumns":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ShowColumns requires 1 args")
			flag.Usage()
		}
		arg530 := flag.Arg(1)
		mbTrans531 := thrift.NewTMemoryBufferLen(len(arg530))
		defer mbTrans531.Close()
		_, err532 := mbTrans531.WriteString(arg530)
		if err532 != nil {
			Usage()
			return
		}
		factory533 := thrift.NewTJSONProtocolFactory()
		jsProt534 := factory533.GetProtocol(mbTrans531)
		argvalue0 := infinity.NewShowColumnsRequest()
		err535 := argvalue0.Read(context.Background(), jsProt534)
		if err535 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ShowColumns(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ShowDatabase":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ShowDatabase requires 1 args")
			flag.Usage()
		}
		arg536 := flag.Arg(1)
		mbTrans537 := thrift.NewTMemoryBufferLen(len(arg536))
		defer mbTrans537.Close()
		_, err538 := mbTrans537.WriteString(arg536)
		if err538 != nil {
			Usage()
			return
		}
		factory539 := thrift.NewTJSONProtocolFactory()
		jsProt540 := factory539.GetProtocol(mbTrans537)
		argvalue0 := infinity.NewShowDatabaseRequest()
		err541 := argvalue0.Read(context.Background(), jsProt540)
		if err541 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ShowDatabase(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ShowSegments":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ShowSegments requires 1 args")
			flag.Usage()
		}
		arg542 := flag.Arg(1)
		mbTrans543 := thrift.NewTMemoryBufferLen(len(arg542))
		defer mbTrans543.Close()
		_, err544 := mbTrans543.WriteString(arg542)
		if err544 != nil {
			Usage()
			return
		}
		factory545 := thrift.NewTJSONProtocolFactory()
		jsProt546 := factory545.GetProtocol(mbTrans543)
		argvalue0 := infinity.NewShowSegmentsRequest()
		err547 := argvalue0.Read(context.Background(), jsProt546)
		if err547 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ShowSegments(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ShowSegment":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ShowSegment requires 1 args")
			flag.Usage()
		}
		arg548 := flag.Arg(1)
		mbTrans549 := thrift.NewTMemoryBufferLen(len(arg548))
		defer mbTrans549.Close()
		_, err550 := mbTrans549.WriteString(arg548)
		if err550 != nil {
			Usage()
			return
		}
		factory551 := thrift.NewTJSONProtocolFactory()
		jsProt552 := factory551.GetProtocol(mbTrans549)
		argvalue0 := infinity.NewShowSegmentRequest()
		err553 := argvalue0.Read(context.Background(), jsProt552)
		if err553 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ShowSegment(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ShowBlocks":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ShowBlocks requires 1 args")
			flag.Usage()
		}
		arg554 := flag.Arg(1)
		mbTrans555 := thrift.NewTMemoryBufferLen(len(arg554))
		defer mbTrans555.Close()
		_, err556 := mbTrans555.WriteString(arg554)
		if err556 != nil {
			Usage()
			return
		}
		factory557 := thrift.NewTJSONProtocolFactory()
		jsProt558 := factory557.GetProtocol(mbTrans555)
		argvalue0 := infinity.NewShowBlocksRequest()
		err559 := argvalue0.Read(context.Background(), jsProt558)
		if err559 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ShowBlocks(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ShowBlock":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ShowBlock requires 1 args")
			flag.Usage()
		}
		arg560 := flag.Arg(1)
		mbTrans561 := thrift.NewTMemoryBufferLen(len(arg560))
		defer mbTrans561.Close()
		_, err562 := mbTrans561.WriteString(arg560)
		if err562 != nil {
			Usage()
			return
		}
		factory563 := thrift.NewTJSONProtocolFactory()
		jsProt564 := factory563.GetProtocol(mbTrans561)
		argvalue0 := infinity.NewShowBlockRequest()
		err565 := argvalue0.Read(context.Background(), jsProt564)
		if err565 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ShowBlock(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ShowBlockColumn":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ShowBlockColumn requires 1 args")
			flag.Usage()
		}
		arg566 := flag.Arg(1)
		mbTrans567 := thrift.NewTMemoryBufferLen(len(arg566))
		defer mbTrans567.Close()
		_, err568 := mbTrans567.WriteString(arg566)
		if err568 != nil {
			Usage()
			return
		}
		factory569 := thrift.NewTJSONProtocolFactory()
		jsProt570 := factory569.GetProtocol(mbTrans567)
		argvalue0 := infinity.NewShowBlockColumnRequest()
		err571 := argvalue0.Read(context.Background(), jsProt570)
		if err571 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ShowBlockColumn(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ShowCurrentNode":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ShowCurrentNode requires 1 args")
			flag.Usage()
		}
		arg572 := flag.Arg(1)
		mbTrans573 := thrift.NewTMemoryBufferLen(len(arg572))
		defer mbTrans573.Close()
		_, err574 := mbTrans573.WriteString(arg572)
		if err574 != nil {
			Usage()
			return
		}
		factory575 := thrift.NewTJSONProtocolFactory()
		jsProt576 := factory575.GetProtocol(mbTrans573)
		argvalue0 := infinity.NewShowCurrentNodeRequest()
		err577 := argvalue0.Read(context.Background(), jsProt576)
		if err577 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ShowCurrentNode(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetDatabase":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDatabase requires 1 args")
			flag.Usage()
		}
		arg578 := flag.Arg(1)
		mbTrans579 := thrift.NewTMemoryBufferLen(len(arg578))
		defer mbTrans579.Close()
		_, err580 := mbTrans579.WriteString(arg578)
		if err580 != nil {
			Usage()
			return
		}
		factory581 := thrift.NewTJSONProtocolFactory()
		jsProt582 := factory581.GetProtocol(mbTrans579)
		argvalue0 := infinity.NewGetDatabaseRequest()
		err583 := argvalue0.Read(context.Background(), jsProt582)
		if err583 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetDatabase(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetTable":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTable requires 1 args")
			flag.Usage()
		}
		arg584 := flag.Arg(1)
		mbTrans585 := thrift.NewTMemoryBufferLen(len(arg584))
		defer mbTrans585.Close()
		_, err586 := mbTrans585.WriteString(arg584)
		if err586 != nil {
			Usage()
			return
		}
		factory587 := thrift.NewTJSONProtocolFactory()
		jsProt588 := factory587.GetProtocol(mbTrans585)
		argvalue0 := infinity.NewGetTableRequest()
		err589 := argvalue0.Read(context.Background(), jsProt588)
		if err589 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetTable(context.Background(), value0))
		fmt.Print("\n")
		break
	case "CreateIndex":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateIndex requires 1 args")
			flag.Usage()
		}
		arg590 := flag.Arg(1)
		mbTrans591 := thrift.NewTMemoryBufferLen(len(arg590))
		defer mbTrans591.Close()
		_, err592 := mbTrans591.WriteString(arg590)
		if err592 != nil {
			Usage()
			return
		}
		factory593 := thrift.NewTJSONProtocolFactory()
		jsProt594 := factory593.GetProtocol(mbTrans591)
		argvalue0 := infinity.NewCreateIndexRequest()
		err595 := argvalue0.Read(context.Background(), jsProt594)
		if err595 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateIndex(context.Background(), value0))
		fmt.Print("\n")
		break
	case "DropIndex":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DropIndex requires 1 args")
			flag.Usage()
		}
		arg596 := flag.Arg(1)
		mbTrans597 := thrift.NewTMemoryBufferLen(len(arg596))
		defer mbTrans597.Close()
		_, err598 := mbTrans597.WriteString(arg596)
		if err598 != nil {
			Usage()
			return
		}
		factory599 := thrift.NewTJSONProtocolFactory()
		jsProt600 := factory599.GetProtocol(mbTrans597)
		argvalue0 := infinity.NewDropIndexRequest()
		err601 := argvalue0.Read(context.Background(), jsProt600)
		if err601 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DropIndex(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ShowIndex":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ShowIndex requires 1 args")
			flag.Usage()
		}
		arg602 := flag.Arg(1)
		mbTrans603 := thrift.NewTMemoryBufferLen(len(arg602))
		defer mbTrans603.Close()
		_, err604 := mbTrans603.WriteString(arg602)
		if err604 != nil {
			Usage()
			return
		}
		factory605 := thrift.NewTJSONProtocolFactory()
		jsProt606 := factory605.GetProtocol(mbTrans603)
		argvalue0 := infinity.NewShowIndexRequest()
		err607 := argvalue0.Read(context.Background(), jsProt606)
		if err607 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ShowIndex(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Optimize":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Optimize requires 1 args")
			flag.Usage()
		}
		arg608 := flag.Arg(1)
		mbTrans609 := thrift.NewTMemoryBufferLen(len(arg608))
		defer mbTrans609.Close()
		_, err610 := mbTrans609.WriteString(arg608)
		if err610 != nil {
			Usage()
			return
		}
		factory611 := thrift.NewTJSONProtocolFactory()
		jsProt612 := factory611.GetProtocol(mbTrans609)
		argvalue0 := infinity.NewOptimizeRequest()
		err613 := argvalue0.Read(context.Background(), jsProt612)
		if err613 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Optimize(context.Background(), value0))
		fmt.Print("\n")
		break
	case "AlterIndex":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "AlterIndex requires 1 args")
			flag.Usage()
		}
		arg614 := flag.Arg(1)
		mbTrans615 := thrift.NewTMemoryBufferLen(len(arg614))
		defer mbTrans615.Close()
		_, err616 := mbTrans615.WriteString(arg614)
		if err616 != nil {
			Usage()
			return
		}
		factory617 := thrift.NewTJSONProtocolFactory()
		jsProt618 := factory617.GetProtocol(mbTrans615)
		argvalue0 := infinity.NewAlterIndexRequest()
		err619 := argvalue0.Read(context.Background(), jsProt618)
		if err619 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.AlterIndex(context.Background(), value0))
		fmt.Print("\n")
		break
	case "AddColumns":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "AddColumns requires 1 args")
			flag.Usage()
		}
		arg620 := flag.Arg(1)
		mbTrans621 := thrift.NewTMemoryBufferLen(len(arg620))
		defer mbTrans621.Close()
		_, err622 := mbTrans621.WriteString(arg620)
		if err622 != nil {
			Usage()
			return
		}
		factory623 := thrift.NewTJSONProtocolFactory()
		jsProt624 := factory623.GetProtocol(mbTrans621)
		argvalue0 := infinity.NewAddColumnsRequest()
		err625 := argvalue0.Read(context.Background(), jsProt624)
		if err625 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.AddColumns(context.Background(), value0))
		fmt.Print("\n")
		break
	case "DropColumns":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DropColumns requires 1 args")
			flag.Usage()
		}
		arg626 := flag.Arg(1)
		mbTrans627 := thrift.NewTMemoryBufferLen(len(arg626))
		defer mbTrans627.Close()
		_, err628 := mbTrans627.WriteString(arg626)
		if err628 != nil {
			Usage()
			return
		}
		factory629 := thrift.NewTJSONProtocolFactory()
		jsProt630 := factory629.GetProtocol(mbTrans627)
		argvalue0 := infinity.NewDropColumnsRequest()
		err631 := argvalue0.Read(context.Background(), jsProt630)
		if err631 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DropColumns(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Cleanup":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Cleanup requires 1 args")
			flag.Usage()
		}
		arg632 := flag.Arg(1)
		mbTrans633 := thrift.NewTMemoryBufferLen(len(arg632))
		defer mbTrans633.Close()
		_, err634 := mbTrans633.WriteString(arg632)
		if err634 != nil {
			Usage()
			return
		}
		factory635 := thrift.NewTJSONProtocolFactory()
		jsProt636 := factory635.GetProtocol(mbTrans633)
		argvalue0 := infinity.NewCommonRequest()
		err637 := argvalue0.Read(context.Background(), jsProt636)
		if err637 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Cleanup(context.Background(), value0))
		fmt.Print("\n")
		break
	case "DumpIndex":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DumpIndex requires 1 args")
			flag.Usage()
		}
		arg638 := flag.Arg(1)
		mbTrans639 := thrift.NewTMemoryBufferLen(len(arg638))
		defer mbTrans639.Close()
		_, err640 := mbTrans639.WriteString(arg638)
		if err640 != nil {
			Usage()
			return
		}
		factory641 := thrift.NewTJSONProtocolFactory()
		jsProt642 := factory641.GetProtocol(mbTrans639)
		argvalue0 := infinity.NewDumpIndexRequest()
		err643 := argvalue0.Read(context.Background(), jsProt642)
		if err643 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DumpIndex(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Command":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Command requires 1 args")
			flag.Usage()
		}
		arg644 := flag.Arg(1)
		mbTrans645 := thrift.NewTMemoryBufferLen(len(arg644))
		defer mbTrans645.Close()
		_, err646 := mbTrans645.WriteString(arg644)
		if err646 != nil {
			Usage()
			return
		}
		factory647 := thrift.NewTJSONProtocolFactory()
		jsProt648 := factory647.GetProtocol(mbTrans645)
		argvalue0 := infinity.NewCommandRequest()
		err649 := argvalue0.Read(context.Background(), jsProt648)
		if err649 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Command(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Flush":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Flush requires 1 args")
			flag.Usage()
		}
		arg650 := flag.Arg(1)
		mbTrans651 := thrift.NewTMemoryBufferLen(len(arg650))
		defer mbTrans651.Close()
		_, err652 := mbTrans651.WriteString(arg650)
		if err652 != nil {
			Usage()
			return
		}
		factory653 := thrift.NewTJSONProtocolFactory()
		jsProt654 := factory653.GetProtocol(mbTrans651)
		argvalue0 := infinity.NewFlushRequest()
		err655 := argvalue0.Read(context.Background(), jsProt654)
		if err655 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Flush(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Compact":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Compact requires 1 args")
			flag.Usage()
		}
		arg656 := flag.Arg(1)
		mbTrans657 := thrift.NewTMemoryBufferLen(len(arg656))
		defer mbTrans657.Close()
		_, err658 := mbTrans657.WriteString(arg656)
		if err658 != nil {
			Usage()
			return
		}
		factory659 := thrift.NewTJSONProtocolFactory()
		jsProt660 := factory659.GetProtocol(mbTrans657)
		argvalue0 := infinity.NewCompactRequest()
		err661 := argvalue0.Read(context.Background(), jsProt660)
		if err661 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Compact(context.Background(), value0))
		fmt.Print("\n")
		break
	case "CreateTableSnapshot":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateTableSnapshot requires 1 args")
			flag.Usage()
		}
		arg662 := flag.Arg(1)
		mbTrans663 := thrift.NewTMemoryBufferLen(len(arg662))
		defer mbTrans663.Close()
		_, err664 := mbTrans663.WriteString(arg662)
		if err664 != nil {
			Usage()
			return
		}
		factory665 := thrift.NewTJSONProtocolFactory()
		jsProt666 := factory665.GetProtocol(mbTrans663)
		argvalue0 := infinity.NewCreateTableSnapshotRequest()
		err667 := argvalue0.Read(context.Background(), jsProt666)
		if err667 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateTableSnapshot(context.Background(), value0))
		fmt.Print("\n")
		break
	case "CreateDatabaseSnapshot":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateDatabaseSnapshot requires 1 args")
			flag.Usage()
		}
		arg668 := flag.Arg(1)
		mbTrans669 := thrift.NewTMemoryBufferLen(len(arg668))
		defer mbTrans669.Close()
		_, err670 := mbTrans669.WriteString(arg668)
		if err670 != nil {
			Usage()
			return
		}
		factory671 := thrift.NewTJSONProtocolFactory()
		jsProt672 := factory671.GetProtocol(mbTrans669)
		argvalue0 := infinity.NewCreateDatabaseSnapshotRequest()
		err673 := argvalue0.Read(context.Background(), jsProt672)
		if err673 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateDatabaseSnapshot(context.Background(), value0))
		fmt.Print("\n")
		break
	case "CreateSystemSnapshot":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateSystemSnapshot requires 1 args")
			flag.Usage()
		}
		arg674 := flag.Arg(1)
		mbTrans675 := thrift.NewTMemoryBufferLen(len(arg674))
		defer mbTrans675.Close()
		_, err676 := mbTrans675.WriteString(arg674)
		if err676 != nil {
			Usage()
			return
		}
		factory677 := thrift.NewTJSONProtocolFactory()
		jsProt678 := factory677.GetProtocol(mbTrans675)
		argvalue0 := infinity.NewCreateSystemSnapshotRequest()
		err679 := argvalue0.Read(context.Background(), jsProt678)
		if err679 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateSystemSnapshot(context.Background(), value0))
		fmt.Print("\n")
		break
	case "RestoreSnapshot":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RestoreSnapshot requires 1 args")
			flag.Usage()
		}
		arg680 := flag.Arg(1)
		mbTrans681 := thrift.NewTMemoryBufferLen(len(arg680))
		defer mbTrans681.Close()
		_, err682 := mbTrans681.WriteString(arg680)
		if err682 != nil {
			Usage()
			return
		}
		factory683 := thrift.NewTJSONProtocolFactory()
		jsProt684 := factory683.GetProtocol(mbTrans681)
		argvalue0 := infinity.NewRestoreSnapshotRequest()
		err685 := argvalue0.Read(context.Background(), jsProt684)
		if err685 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RestoreSnapshot(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ShowSnapshot":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ShowSnapshot requires 1 args")
			flag.Usage()
		}
		arg686 := flag.Arg(1)
		mbTrans687 := thrift.NewTMemoryBufferLen(len(arg686))
		defer mbTrans687.Close()
		_, err688 := mbTrans687.WriteString(arg686)
		if err688 != nil {
			Usage()
			return
		}
		factory689 := thrift.NewTJSONProtocolFactory()
		jsProt690 := factory689.GetProtocol(mbTrans687)
		argvalue0 := infinity.NewShowSnapshotRequest()
		err691 := argvalue0.Read(context.Background(), jsProt690)
		if err691 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ShowSnapshot(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ListSnapshots":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ListSnapshots requires 1 args")
			flag.Usage()
		}
		arg692 := flag.Arg(1)
		mbTrans693 := thrift.NewTMemoryBufferLen(len(arg692))
		defer mbTrans693.Close()
		_, err694 := mbTrans693.WriteString(arg692)
		if err694 != nil {
			Usage()
			return
		}
		factory695 := thrift.NewTJSONProtocolFactory()
		jsProt696 := factory695.GetProtocol(mbTrans693)
		argvalue0 := infinity.NewListSnapshotsRequest()
		err697 := argvalue0.Read(context.Background(), jsProt696)
		if err697 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListSnapshots(context.Background(), value0))
		fmt.Print("\n")
		break
	case "DropSnapshot":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DropSnapshot requires 1 args")
			flag.Usage()
		}
		arg698 := flag.Arg(1)
		mbTrans699 := thrift.NewTMemoryBufferLen(len(arg698))
		defer mbTrans699.Close()
		_, err700 := mbTrans699.WriteString(arg698)
		if err700 != nil {
			Usage()
			return
		}
		factory701 := thrift.NewTJSONProtocolFactory()
		jsProt702 := factory701.GetProtocol(mbTrans699)
		argvalue0 := infinity.NewDropSnapshotRequest()
		err703 := argvalue0.Read(context.Background(), jsProt702)
		if err703 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DropSnapshot(context.Background(), value0))
		fmt.Print("\n")
		break
	case "SetConfig":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SetConfig requires 1 args")
			flag.Usage()
		}
		arg704 := flag.Arg(1)
		mbTrans705 := thrift.NewTMemoryBufferLen(len(arg704))
		defer mbTrans705.Close()
		_, err706 := mbTrans705.WriteString(arg704)
		if err706 != nil {
			Usage()
			return
		}
		factory707 := thrift.NewTJSONProtocolFactory()
		jsProt708 := factory707.GetProtocol(mbTrans705)
		argvalue0 := infinity.NewSetConfigRequest()
		err709 := argvalue0.Read(context.Background(), jsProt708)
		if err709 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SetConfig(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ShowConfig":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ShowConfig requires 1 args")
			flag.Usage()
		}
		arg710 := flag.Arg(1)
		mbTrans711 := thrift.NewTMemoryBufferLen(len(arg710))
		defer mbTrans711.Close()
		_, err712 := mbTrans711.WriteString(arg710)
		if err712 != nil {
			Usage()
			return
		}
		factory713 := thrift.NewTJSONProtocolFactory()
		jsProt714 := factory713.GetProtocol(mbTrans711)
		argvalue0 := infinity.NewShowConfigRequest()
		err715 := argvalue0.Read(context.Background(), jsProt714)
		if err715 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ShowConfig(context.Background(), value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
