name: Subtask
description: "Propose a subtask for infinity"
title: "[Subtask]: "
labels: [subtask]

body:
  - type: textarea
    attributes:
      label: Parent Issue
      description: Write the ID of the parent issue
      placeholder: "Parent issue: #"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Detail of Subtask
      description: |
        Describe the functions that this subtask should implement
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe implementation you've considered
      description: A clear and concise description of implementation you've considered or investigated.
    validations:
      required: false

