#!/usr/bin/bash

if ! id -u infinity > /dev/null 2>&1 ; then
    useradd --create-home --home-dir /var/infinity --skel /dev/null infinity
fi

mkdir -p /var/infinity && chown -R infinity /var/infinity

mkdir -p /usr/share/infinity/resource && chown -R infinity /usr/share/infinity/resource
