FROM ubuntu:23.10

RUN sed -i 's@//.*archive.ubuntu.com@//mirrors.tuna.tsinghua.edu.cn@g' /etc/apt/sources.list
RUN apt update

# Clang 17+ is required for C++20 modules. GCC is not supported.
RUN apt install -y clang-*-17 libc++-17-dev llvm-17
RUN ln -s /usr/bin/clang-scan-deps-17 /usr/bin/clang-scan-deps && ln -s /usr/bin/clang-format-17 /usr/bin/clang-format && ln -s /usr/bin/clang-tidy-17 /usr/bin/clang-tidy && ln -s /usr/bin/llvm-symbolizer-17 /usr/bin/llvm-symbolizer

ENV CC=/usr/bin/clang-17
ENV CXX=/usr/bin/clang++-17

# tools
RUN apt install -y wget curl emacs-nox vim git build-essential ninja-build bison flex thrift-compiler postgresql-client python3-full tree rpm

# build dependencies
RUN apt install -y liblz4-dev zlib1g-dev libboost1.81-dev liburing-dev libgflags-dev libevent-dev libjemalloc-dev python3-dev

# CMake 3.28+ is required for C++20 modules.
# download https://github.com/Kitware/CMake/releases/download/v3.29.3/cmake-3.29.3-linux-x86_64.tar.gz
RUN --mount=type=bind,source=cmake-3.29.3-linux-x86_64.tar.gz,target=/root/cmake-3.29.3-linux-x86_64.tar.gz \
    cd /root && tar xzf cmake-3.29.3-linux-x86_64.tar.gz && cp -rf cmake-3.29.3-linux-x86_64/bin/* /usr/local/bin && cp -rf cmake-3.29.3-linux-x86_64/share/* /usr/local/share && rm -fr cmake-3.29.3-linux-x86_64

# download https://github.com/gperftools/gperftools/releases/download/gperftools-2.15/gperftools-2.15.tar.gz
RUN --mount=type=bind,source=gperftools-2.15.tar.gz,target=/root/gperftools-2.15.tar.gz \
    cd /root && tar xzf gperftools-2.15.tar.gz && cd gperftools-2.15 && ./configure && make -j 8 && make install && rm -fr /root/gperftools-2.15

# download https://github.com/risinglightdb/sqllogictest-rs/releases/download/v0.20.2/sqllogictest-bin-v0.20.2-x86_64-unknown-linux-musl.tar.gz
RUN --mount=type=bind,source=sqllogictest-bin-v0.20.2-x86_64-unknown-linux-musl.tar.gz,target=/root/sqllogictest-bin-v0.20.2-x86_64-unknown-linux-musl.tar.gz \
    cd /tmp && tar xzf /root/sqllogictest-bin-v0.20.2-x86_64-unknown-linux-musl.tar.gz && cp -rf sqllogictest /usr/local/bin && rm -fr /tmp/*

# Create a python virtual environment. Set PATH so that the shell activate this virtual environment automatically when entering a container from this image.
RUN python3 -m venv /usr/local/venv
ENV PATH="/usr/local/venv/bin:$PATH"
RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple/ && pip3 config set global.trusted-host pypi.tuna.tsinghua.edu.cn && pip3 install wheel twine

# infinity python SDK dependencies
COPY python/requirements.txt .
RUN --mount=type=bind,source=python/requirements.txt,target=/root/requirements.txt pip3 install --no-input -r /root/requirements.txt

ENTRYPOINT [ "bash", "-c", "while true; do sleep 60; done"]
