# NOTICE: This Dockerfile depends on BuildKit
# NOTICE: You must run download_deps_infinity_builder_ubuntu20.sh script BEFORE building this image

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

# Configure APT to use USTC mirrors and install basic packages
RUN --mount=type=cache,id=inf_apt,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=inf_lib,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y ca-certificates \
    && sed -i 's|http://archive.ubuntu.com|https://mirrors.ustc.edu.cn|g' /etc/apt/sources.list \
    && sed -i 's|http://security.ubuntu.com|https://mirrors.ustc.edu.cn|g' /etc/apt/sources.list \
    && apt-get update && apt-get install -y \
        git make wget curl vim file gettext \
        libssl-dev unzip bzip2 libtool m4 tree \
        autoconf automake pkg-config \
        software-properties-common gnupg2 lsb-release \
        build-essential zlib1g-dev libncurses5-dev libgdbm-dev \
        libnss3-dev libreadline-dev libffi-dev libsqlite3-dev \
        libbz2-dev libexpat1-dev liblzma-dev tk-dev uuid-dev \
        postgresql graphviz sudo bridge-utils iptables \
        libpcap-dev libpcre3-dev \
        perl flex bison binutils gdb zip rpm iproute2\
    && echo '/usr/local/lib' >> /etc/ld.so.conf.d/local.conf \
    && echo '/usr/local/lib64' >> /etc/ld.so.conf.d/local.conf

# Add LLVM APT repository and install clang 20
RUN --mount=type=cache,id=inf_apt,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=inf_lib,target=/var/lib/apt,sharing=locked \
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
    && echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-20 main" >> /etc/apt/sources.list.d/llvm.list \
    && echo "deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-20 main" >> /etc/apt/sources.list.d/llvm.list \
    && apt-get update \
    && apt-get install -y \
        clang-20 clang++-20 clang-format-20 clang-tidy-20 clang-tools-20 \
        libc++-20-dev libc++abi-20-dev \
        lld-20 lldb-20 \
    && update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 100 \
    && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 100 \
    && update-alternatives --install /usr/bin/lld lld /usr/bin/lld-20 100

# Install GCC 15 build dependencies
RUN --mount=type=cache,id=inf_apt,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=inf_lib,target=/var/lib/apt,sharing=locked \
    apt install -y libgmp-dev libmpfr-dev libmpc-dev libisl-dev

# Install GCC 15 from source with complete libstdc++ support
RUN --mount=type=bind,source=gcc-15.2.0.tar.gz,target=/root/gcc-15.2.0.tar.gz \
    cd /root && tar xf gcc-15.2.0.tar.gz \
    && cd gcc-releases-gcc-15.2.0 && mkdir build && cd build \
    && ../configure --prefix=/usr \
        --enable-languages=c,c++ \
        --enable-shared \
        --enable-static \
        --enable-libstdcxx \
        --enable-libstdcxx-time \
        --enable-libstdcxx-filesystem-ts \
        --disable-multilib \
        --with-system-zlib \
        --program-suffix=-15 \
    && make -j$(nproc) \
    && make install \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-15 150 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-15 150 \
    && update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-15 150 \
    && cd /root && rm -rf gcc-releases-gcc-15.2.0

# Configure GCC 15 library paths and symlinks for infinity build system
RUN mkdir -p /usr/lib64/gcc/15 \
    && mkdir -p /usr/lib64/gcc/x86_64-linux-gnu/15 \
    # Copy static libraries to expected locations
    && cp /usr/lib64/libstdc++.a /usr/lib64/gcc/15/ \
    && cp /usr/lib64/libstdc++exp.a /usr/lib64/gcc/15/ \
    && cp /usr/lib64/libstdc++.a /usr/lib64/gcc/x86_64-linux-gnu/15/ \
    && cp /usr/lib64/libstdc++exp.a /usr/lib64/gcc/x86_64-linux-gnu/15/ \
    # Update library paths and ensure new libstdc++ is used
    && echo "/usr/lib64" >> /etc/ld.so.conf.d/gcc-15.conf \
    && echo "/usr/lib/x86_64-linux-gnu" >> /etc/ld.so.conf.d/gcc-15.conf \
    && ldconfig \
    # Create symlinks for dynamic libraries
    && ln -sf /usr/lib64/libstdc++.so.6.0.34 /lib/x86_64-linux-gnu/libstdc++.so.6 \
    && ln -sf /usr/lib64/libstdc++.so.6.0.34 /usr/lib/x86_64-linux-gnu/libstdc++.so.6 \
    # Verify the symlink points to the correct version
    && ls -la /lib/x86_64-linux-gnu/libstdc++.so.6

# Install Python 3.10 from source
RUN --mount=type=bind,source=Python-3.10.18.tar.xz,target=/root/Python-3.10.18.tar.xz \
    cd /root && tar xJf Python-3.10.18.tar.xz \
    && cd Python-3.10.18 && ./configure --enable-shared \
    && make -j$(nproc) && make altinstall \
    && ldconfig && cd /root && rm -rf Python-3.10.18 \
    && update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.10 50 \
    && update-alternatives --install /usr/bin/pip3 pip3 /usr/local/bin/pip3.10 50

# Install cmake-4.1.0
RUN --mount=type=bind,source=cmake-4.1.0-linux-x86_64.tar.gz,target=/root/cmake-4.1.0-linux-x86_64.tar.gz \
    cd /root && tar xf cmake-4.1.0-linux-x86_64.tar.gz \
    && cp -rf cmake-4.1.0-linux-x86_64/bin/* /usr/local/bin \
    && cp -rf cmake-4.1.0-linux-x86_64/share/* /usr/local/share \
    && rm -rf cmake-4.1.0-linux-x86_64

# Install ninja-1.13.1
RUN --mount=type=bind,source=ninja-linux.zip,target=/root/ninja-linux.zip \
    cd /root && unzip ninja-linux.zip \
    && cp ninja /usr/local/bin

# Install jemalloc-5.3.0
# Known issue: Composition of `-fsanitize=address`, staticly linked jemalloc and `mallctl` cause crash at initialization.
# Refers to https://github.com/jemalloc/jemalloc/issues/2454
RUN --mount=type=bind,source=jemalloc-5.3.0.tar.bz2,target=/root/jemalloc-5.3.0.tar.bz2  \
    cd /root && tar xjf jemalloc-5.3.0.tar.bz2 \
    && cd jemalloc-5.3.0 && CFLAGS="-fPIC" CXXFLAGS="-fPIC" ./configure --enable-static --disable-libdl --enable-prof --enable-prof-libunwind --disable-initial-exec-tls && make -j install \
    && ldconfig && cd /root && rm -rf jemalloc-5.3.0

# Install gperftools-2.17
RUN --mount=type=bind,source=gperftools-2.17.tar.gz,target=/root/gperftools-2.17.tar.gz  \
    cd /root && tar xzf gperftools-2.17.tar.gz \
    && cd gperftools-2.17 && ./configure && make -j && make install \
    && ldconfig && cd /root && rm -rf gperftools-2.17

# Install sqllogictest
RUN --mount=type=bind,source=sqllogictest-bin-v0.28.3-x86_64-unknown-linux-musl.tar.gz,target=/root/sqllogictest-bin-v0.28.3-x86_64-unknown-linux-musl.tar.gz \
    cd /tmp && tar xzf /root/sqllogictest-bin-v0.28.3-x86_64-unknown-linux-musl.tar.gz && cp -rf sqllogictest /usr/local/bin && rm -fr /tmp/*

# Install mold-2.40.3
RUN --mount=type=bind,source=mold-2.40.3-x86_64-linux.tar.gz,target=/root/mold-2.40.3-x86_64-linux.tar.gz \
    cd /root && tar xf mold-2.40.3-x86_64-linux.tar.gz \
    && cp -rf mold-2.40.3-x86_64-linux/bin/* /usr/local/bin \
    && cp -rf mold-2.40.3-x86_64-linux/lib/* /usr/local/lib \
    && cp -rf mold-2.40.3-x86_64-linux/libexec/* /usr/local/libexec \
    && rm -rf mold-2.40.3-x86_64-linux

# Install Docker
RUN --mount=type=bind,source=docker-28.3.3.tgz,target=/root/docker-28.3.3.tgz \
    cd /root \
    && tar zxf docker-28.3.3.tgz \
    && cp docker/* /usr/bin

# Set environment variables for vcpkg and infinity build
ENV CC=clang CXX=clang++

# Setup vcpkg for manifest mode (no global VCPKG_ROOT)
RUN git clone https://github.com/microsoft/vcpkg.git /opt/vcpkg \
    && cd /opt/vcpkg \
    && ./bootstrap-vcpkg.sh --disableMetrics

# Pre-build vcpkg dependencies using manifest mode
# This populates the binary cache at /root/.cache/vcpkg for later use by infinity builds
RUN --mount=type=bind,source=vcpkg.json,target=/opt/vcpkg/vcpkg.json \
    cd /opt/vcpkg && \
    /opt/vcpkg/vcpkg install --clean-after-build

# Set vcpkg toolchain path for CMake
# Set Python paths for CMake to find the correct Python installation
ENV CMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake  \
    Python3_EXECUTABLE=/usr/local/bin/python3.10 \
    Python3_INCLUDE_DIR=/usr/local/include/python3.10 \
    Python3_LIBRARY=/usr/local/lib/libpython3.10.so

# Add thrift compiler to PATH
RUN ln -s /opt/vcpkg/vcpkg_installed/x64-linux/tools/thrift/thrift /usr/local/bin/thrift

RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple && pip3 config set global.trusted-host mirrors.aliyun.com

# Install infinity python sdk and other packages for later use by infinity tests
RUN --mount=type=bind,source=python/requirements.txt,target=/root/requirements_1.txt --mount=type=bind,source=python/benchmark/requirements.txt,target=/root/requirements_2.txt  --mount=type=bind,source=python/restart_test/requirements.txt,target=/root/requirements_3.txt --mount=type=bind,source=python/test_cluster/requirements.txt,target=/root/requirements_4.txt \
    pip3 install --no-input wheel auditwheel patchelf twine \
    && pip3 install --no-input -r /root/requirements_1.txt -r /root/requirements_2.txt -r /root/requirements_3.txt -r /root/requirements_4.txt

ENTRYPOINT [ "bash", "-c", "while true; do sleep 60; done"]
