FROM debian:stable-slim

RUN apt update -y && apt install -y curl && apt clean -y
# https://docs.docker.com/reference/dockerfile/#copy
# If <src> is a directory, the entire contents of the directory are copied, including filesystem metadata.
# The directory itself isn't copied, only its contents.
COPY cmake-build-reldeb/src/infinity /usr/bin

ENTRYPOINT ["/usr/bin/infinity"]
