# NOTICE: This Dockerfile depends on BuildKit
# NOTICE: You must run download_deps_infinity_builder_ubuntu20.py script BEFORE building this image

FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV VCPKG_ROOT=/opt/vcpkg
COPY nltk_data /root/nltk_data

SHELL ["/bin/bash", "-c"]

COPY vcpkg.json /tmp

# https://www.cnblogs.com/sparkdev/p/9573248.html
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install ca-certificates -y \
    && sed -i 's|http://|https://|g' /etc/apt/sources.list \
    && for f in "mozilla/BJCA_Global_Root_CA1.crt" "mozilla/BJCA_Global_Root_CA2.crt" "mozilla/CFCA_EV_ROOT.crt" "mozilla/GDCA_TrustAUTH_R5_ROOT.crt" "mozilla/Hongkong_Post_Root_CA_3.crt" "mozilla/TrustAsia_Global_Root_CA_G3.crt" "mozilla/TrustAsia_Global_Root_CA_G4.crt" "mozilla/vTrus_ECC_Root_CA.crt" "mozilla/vTrus_Root_CA.crt"; do sed -i "\#^$f\$#d" /etc/ca-certificates.conf; done \
    && update-ca-certificates --fresh \
    && apt-get install -y software-properties-common debconf-utils \
    && echo "apt-fast apt-fast/aptmanager select apt-get" | debconf-set-selections \
    && echo "debconf apt-fast/maxdownloads string 16" | debconf-set-selections \
    && add-apt-repository -y ppa:apt-fast/stable \
    && DEBIAN_FRONTEND=noninteractive \
    APT_LISTCHANGES_FRONTEND=none \
    apt-get -y -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold" install apt-fast \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-fast -y update \
    && apt-fast install -y \
    git make curl vim file gettext \
    libssl-dev unzip bzip2 libtool m4 tree \
    autoconf automake pkg-config autoconf-archive libtool \
    software-properties-common gnupg2 lsb-release \
    build-essential zlib1g-dev libncurses5-dev libgdbm-dev \
    libnss3-dev libreadline-dev libffi-dev libsqlite3-dev \
    libbz2-dev libexpat1-dev liblzma-dev tk-dev uuid-dev \
    postgresql graphviz sudo bridge-utils iptables \
    libpcap-dev libpcre3-dev \
    perl flex bison binutils zip rpm iproute2 \
    libgmp-dev libmpfr-dev libmpc-dev libisl-dev \
    python3.11-dev \
    && mkdir infinity_download && cd infinity_download \
    && printf '%s\n' \
    'https://github.com/Kitware/CMake/releases/download/v4.2.5/cmake-4.2.5-linux-x86_64.tar.gz' \
    'https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux.zip' \
    'https://github.com/gperftools/gperftools/releases/download/gperftools-2.18.1/gperftools-2.18.1.tar.gz' \
    'https://github.com/risinglightdb/sqllogictest-rs/releases/download/v0.29.1/sqllogictest-bin-v0.29.1-x86_64-unknown-linux-musl.tar.gz' \
    'https://github.com/rui314/mold/releases/download/v2.41.0/mold-2.41.0-x86_64-linux.tar.gz' \
    'https://developer.arm.com/-/media/Files/downloads/gnu/15.2.rel1/binrel/arm-gnu-toolchain-15.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz' \
    'https://github.com/tttapa/toolchains/releases/latest/download/x-tools-x86_64-focal-linux-gnu-gcc15.tar.xz' \
    'https://download.docker.com/linux/static/stable/x86_64/docker-29.5.2.tgz' \
    'https://astral.sh/uv/install.sh' \
    'https://apt.llvm.org/llvm.sh' \
    > downloads.txt  \
    && aria2c -j 16 --min-split-size 1M -i downloads.txt \
    && chmod +x llvm.sh && sed -i 's|apt-get|apt-fast|g' llvm.sh && ./llvm.sh 20 \
    && tar xf cmake-4.2.5-linux-x86_64.tar.gz \
    && cp -rf cmake-4.2.5-linux-x86_64/bin/* /usr/local/bin \
    && cp -rf cmake-4.2.5-linux-x86_64/share/* /usr/local/share \
    && unzip ninja-linux.zip \
    && cp ninja /usr/local/bin \
    && tar xzf gperftools-2.18.1.tar.gz \
    && cd gperftools-2.18.1 && ./configure && make -j && make install && ldconfig && cd .. \
    && tar xzf sqllogictest-bin-v0.29.1-x86_64-unknown-linux-musl.tar.gz && cp -rf sqllogictest /usr/local/bin \
    && tar xf mold-2.41.0-x86_64-linux.tar.gz \
    && cp -rf mold-2.41.0-x86_64-linux/bin/* /usr/local/bin \
    && cp -rf mold-2.41.0-x86_64-linux/lib/* /usr/local/lib \
    && cp -rf mold-2.41.0-x86_64-linux/libexec/* /usr/local/libexec \
    && tar xzf docker-29.5.2.tgz \
    && cp docker/* /usr/bin \
    && chmod +x uv-installer.sh && ./uv-installer.sh \
    && mkdir /arm-gnu-toolchain-15.2.rel1-x86_64-aarch64-none-linux-gnu \
    && tar xJf arm-gnu-toolchain-15.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz -C /arm-gnu-toolchain-15.2.rel1-x86_64-aarch64-none-linux-gnu \
    && tar xJf x-tools-x86_64-focal-linux-gnu-gcc15.tar.xz -C /arm-gnu-toolchain-15.2.rel1-x86_64-aarch64-none-linux-gnu \
    && cd .. && rm -rf infinity_download \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 311 \
    && cd /opt && git clone https://github.com/microsoft/vcpkg.git \
    && cd /opt/vcpkg \
    && git checkout $(grep '"builtin-baseline"' /tmp/vcpkg.json | cut -d '"' -f 4) \
    && ./bootstrap-vcpkg.sh --disableMetrics \
    && cp /tmp/vcpkg.json vcpkg.json \
    && ./vcpkg install --clean-after-build

ENTRYPOINT [ "bash", "-c", "while true; do sleep 60; done"]
