# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import infinity_grpc_pb2 as infinity__grpc__pb2


class InfinityGrpcServiceStub(object):
    """network
    """

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/Connect',
            request_serializer=infinity__grpc__pb2.Empty.SerializeToString,
            response_deserializer=infinity__grpc__pb2.CommonResponse.FromString,
        )
        self.DisConnect = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/DisConnect',
            request_serializer=infinity__grpc__pb2.DisConnectRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.CommonResponse.FromString,
        )
        self.CreateDatabase = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/CreateDatabase',
            request_serializer=infinity__grpc__pb2.CreateDatabaseRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.CommonResponse.FromString,
        )
        self.DropDatabase = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/DropDatabase',
            request_serializer=infinity__grpc__pb2.DropDatabaseRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.CommonResponse.FromString,
        )
        self.ListDatabase = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/ListDatabase',
            request_serializer=infinity__grpc__pb2.ListDatabaseRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.ListDatabaseResponse.FromString,
        )
        self.DescribeDatabase = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/DescribeDatabase',
            request_serializer=infinity__grpc__pb2.DescribeDatabaseRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.DescribeDatabaseResponse.FromString,
        )
        self.GetDatabase = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/GetDatabase',
            request_serializer=infinity__grpc__pb2.GetDatabaseRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.CommonResponse.FromString,
        )
        self.CreateTable = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/CreateTable',
            request_serializer=infinity__grpc__pb2.CreateTableRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.CommonResponse.FromString,
        )
        self.DropTable = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/DropTable',
            request_serializer=infinity__grpc__pb2.DropTableRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.CommonResponse.FromString,
        )
        self.ListTable = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/ListTable',
            request_serializer=infinity__grpc__pb2.ListTableRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.ListTableResponse.FromString,
        )
        self.DescribeTable = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/DescribeTable',
            request_serializer=infinity__grpc__pb2.DescribeTableRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.DescribeTableResponse.FromString,
        )
        self.GetTable = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/GetTable',
            request_serializer=infinity__grpc__pb2.GetTableRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.CommonResponse.FromString,
        )
        self.Insert = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/Insert',
            request_serializer=infinity__grpc__pb2.InsertRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.CommonResponse.FromString,
        )
        self.Import = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/Import',
            request_serializer=infinity__grpc__pb2.ImportRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.CommonResponse.FromString,
        )
        self.CreateIndex = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/CreateIndex',
            request_serializer=infinity__grpc__pb2.CreateIndexRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.CommonResponse.FromString,
        )
        self.DropIndex = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/DropIndex',
            request_serializer=infinity__grpc__pb2.DropIndexRequest.SerializeToString,
            response_deserializer=infinity__grpc__pb2.CommonResponse.FromString,
        )
        self.Search = channel.unary_unary(
            '/infinity_grpc_proto.InfinityGrpcService/Search',
            request_serializer=infinity__grpc__pb2.SelectStatement.SerializeToString,
            response_deserializer=infinity__grpc__pb2.SelectResponse.FromString,
        )


class InfinityGrpcServiceServicer(object):
    """network
    """

    def Connect(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisConnect(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDatabase(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropDatabase(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatabase(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeDatabase(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatabase(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTable(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropTable(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTable(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeTable(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTable(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Import(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIndex(self, request, context):
        """rpc Update(Update) returns (Empty);
        rpc Delete(Delete) returns (Empty);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropIndex(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InfinityGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Connect': grpc.unary_unary_rpc_method_handler(
            servicer.Connect,
            request_deserializer=infinity__grpc__pb2.Empty.FromString,
            response_serializer=infinity__grpc__pb2.CommonResponse.SerializeToString,
        ),
        'DisConnect': grpc.unary_unary_rpc_method_handler(
            servicer.DisConnect,
            request_deserializer=infinity__grpc__pb2.DisConnectRequest.FromString,
            response_serializer=infinity__grpc__pb2.CommonResponse.SerializeToString,
        ),
        'CreateDatabase': grpc.unary_unary_rpc_method_handler(
            servicer.CreateDatabase,
            request_deserializer=infinity__grpc__pb2.CreateDatabaseRequest.FromString,
            response_serializer=infinity__grpc__pb2.CommonResponse.SerializeToString,
        ),
        'DropDatabase': grpc.unary_unary_rpc_method_handler(
            servicer.DropDatabase,
            request_deserializer=infinity__grpc__pb2.DropDatabaseRequest.FromString,
            response_serializer=infinity__grpc__pb2.CommonResponse.SerializeToString,
        ),
        'ListDatabase': grpc.unary_unary_rpc_method_handler(
            servicer.ListDatabase,
            request_deserializer=infinity__grpc__pb2.ListDatabaseRequest.FromString,
            response_serializer=infinity__grpc__pb2.ListDatabaseResponse.SerializeToString,
        ),
        'DescribeDatabase': grpc.unary_unary_rpc_method_handler(
            servicer.DescribeDatabase,
            request_deserializer=infinity__grpc__pb2.DescribeDatabaseRequest.FromString,
            response_serializer=infinity__grpc__pb2.DescribeDatabaseResponse.SerializeToString,
        ),
        'GetDatabase': grpc.unary_unary_rpc_method_handler(
            servicer.GetDatabase,
            request_deserializer=infinity__grpc__pb2.GetDatabaseRequest.FromString,
            response_serializer=infinity__grpc__pb2.CommonResponse.SerializeToString,
        ),
        'CreateTable': grpc.unary_unary_rpc_method_handler(
            servicer.CreateTable,
            request_deserializer=infinity__grpc__pb2.CreateTableRequest.FromString,
            response_serializer=infinity__grpc__pb2.CommonResponse.SerializeToString,
        ),
        'DropTable': grpc.unary_unary_rpc_method_handler(
            servicer.DropTable,
            request_deserializer=infinity__grpc__pb2.DropTableRequest.FromString,
            response_serializer=infinity__grpc__pb2.CommonResponse.SerializeToString,
        ),
        'ListTable': grpc.unary_unary_rpc_method_handler(
            servicer.ListTable,
            request_deserializer=infinity__grpc__pb2.ListTableRequest.FromString,
            response_serializer=infinity__grpc__pb2.ListTableResponse.SerializeToString,
        ),
        'DescribeTable': grpc.unary_unary_rpc_method_handler(
            servicer.DescribeTable,
            request_deserializer=infinity__grpc__pb2.DescribeTableRequest.FromString,
            response_serializer=infinity__grpc__pb2.DescribeTableResponse.SerializeToString,
        ),
        'GetTable': grpc.unary_unary_rpc_method_handler(
            servicer.GetTable,
            request_deserializer=infinity__grpc__pb2.GetTableRequest.FromString,
            response_serializer=infinity__grpc__pb2.CommonResponse.SerializeToString,
        ),
        'Insert': grpc.unary_unary_rpc_method_handler(
            servicer.Insert,
            request_deserializer=infinity__grpc__pb2.InsertRequest.FromString,
            response_serializer=infinity__grpc__pb2.CommonResponse.SerializeToString,
        ),
        'Import': grpc.unary_unary_rpc_method_handler(
            servicer.Import,
            request_deserializer=infinity__grpc__pb2.ImportRequest.FromString,
            response_serializer=infinity__grpc__pb2.CommonResponse.SerializeToString,
        ),
        'CreateIndex': grpc.unary_unary_rpc_method_handler(
            servicer.CreateIndex,
            request_deserializer=infinity__grpc__pb2.CreateIndexRequest.FromString,
            response_serializer=infinity__grpc__pb2.CommonResponse.SerializeToString,
        ),
        'DropIndex': grpc.unary_unary_rpc_method_handler(
            servicer.DropIndex,
            request_deserializer=infinity__grpc__pb2.DropIndexRequest.FromString,
            response_serializer=infinity__grpc__pb2.CommonResponse.SerializeToString,
        ),
        'Search': grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=infinity__grpc__pb2.SelectStatement.FromString,
            response_serializer=infinity__grpc__pb2.SelectResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'infinity_grpc_proto.InfinityGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
